// ABOUTME: SDK-side helpers for unshield — generateUnshieldProof + populateProvedUnshield. Direct user-submitted tx (no relayer for v1).
// ABOUTME: Dynamic-imports the Railgun SDK + shared-models to dodge jsdom's circomlibjs crash; the populated tx hash gets submitted by features/unshield/handler.

import { loadHubNetwork } from './network'

type RailgunSdk = typeof import('@railgun-community/wallet')
type SharedModels = typeof import('@railgun-community/shared-models')

async function railgunSdk(): Promise<RailgunSdk> {
  return import('@railgun-community/wallet')
}
async function sharedModels(): Promise<SharedModels> {
  return import('@railgun-community/shared-models')
}

/**
 * Gas details used for both proof generation (informs the proof of the gas estimate) and the
 * actual tx submission. Values mirror legacy/usdc-v2-frontend — EIP-1559 (Type2) because Hardhat
 * (and our patched Railgun NetworkName.Hardhat) require it.
 *
 * 2 000 000 gas / 2 gwei max / 1 gwei priority — overkill for local but harmless; the user pays
 * actual usage. When Sepolia mode lands we'll likely sharpen these per chain.
 */
async function buildGasDetails(): Promise<unknown> {
  const { EVMGasType } = await sharedModels()
  return {
    evmGasType: EVMGasType.Type2,
    gasEstimate: 2_000_000n,
    maxFeePerGas: 2_000_000_000n,
    maxPriorityFeePerGas: 1_000_000_000n,
  }
}

/**
 * Generate the ZK unshield proof for a single recipient. Side-effect on the engine: the proof
 * is cached in memory keyed by the wallet + amounts, and the subsequent `populateProvedUnshield`
 * call must use the SAME inputs or it throws "proof not found".
 *
 * `onProgress` receives a value in [0, 1]; the SDK calls it ~10× over the proof generation
 * window (which is 20-30 seconds on local Anvil, longer on slower machines).
 */
export async function generateUnshieldProofForRecipient(opts: {
  walletId: string
  encryptionKey: string
  tokenAddress: string
  recipient: string
  amount: bigint
  onProgress?: (fraction: number) => void
}): Promise<void> {
  await loadHubNetwork()
  const [{ generateUnshieldProof }, { TXIDVersion, NetworkName }] = await Promise.all([
    railgunSdk(),
    sharedModels(),
  ])
  await generateUnshieldProof(
    TXIDVersion.V2_PoseidonMerkle,
    NetworkName.Hardhat,
    opts.walletId,
    opts.encryptionKey,
    [
      {
        tokenAddress: opts.tokenAddress,
        amount: opts.amount,
        recipientAddress: opts.recipient,
      },
    ],
    [], // nftAmountRecipients
    undefined, // broadcasterFeeRecipient — direct user submit, no relayer fee
    true, // sendWithPublicWallet
    undefined, // overallBatchMinGasPrice
    (progress) => opts.onProgress?.(progress / 100),
  )
}

/**
 * Populate the transaction object using the proof generated by `generateUnshieldProofForRecipient`.
 * Inputs MUST match the proof call exactly (walletId, recipient, amount, token).
 *
 * Returns the raw `to` + `data` + `value` from the SDK — the handler signs+submits via the
 * connected wallet rather than letting the SDK call its own provider (which would use a
 * non-user signer).
 */
export async function populateUnshieldTransaction(opts: {
  walletId: string
  tokenAddress: string
  recipient: string
  amount: bigint
}): Promise<{ to: `0x${string}`; data: `0x${string}`; value: bigint }> {
  const [{ populateProvedUnshield }, { TXIDVersion, NetworkName }] = await Promise.all([
    railgunSdk(),
    sharedModels(),
  ])
  const gasDetails = await buildGasDetails()
  const result = await populateProvedUnshield(
    TXIDVersion.V2_PoseidonMerkle,
    NetworkName.Hardhat,
    opts.walletId,
    [
      {
        tokenAddress: opts.tokenAddress,
        amount: opts.amount,
        recipientAddress: opts.recipient,
      },
    ],
    [], // nftAmountRecipients
    undefined, // broadcasterFeeRecipient
    true, // sendWithPublicWallet
    undefined, // overallBatchMinGasPrice
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    gasDetails as any,
  )
  const tx = result.transaction
  if (!tx.to || !tx.data) {
    throw new Error('populateUnshieldTransaction: SDK returned an incomplete transaction')
  }
  return {
    to: tx.to as `0x${string}`,
    data: tx.data as `0x${string}`,
    value: tx.value ? BigInt(tx.value.toString()) : 0n,
  }
}
