// ABOUTME: SDK-side helpers for unshield — generateUnshieldProof + populateProvedUnshield. Direct user-submitted tx (no relayer for v1).
// ABOUTME: Dynamic-imports the Railgun SDK + shared-models to dodge jsdom's circomlibjs crash; the populated tx hash gets submitted by features/unshield/handler.

import { loadHubNetwork } from './network'

type RailgunSdk = typeof import('@railgun-community/wallet')
type SharedModels = typeof import('@railgun-community/shared-models')

async function railgunSdk(): Promise<RailgunSdk> {
  return import('@railgun-community/wallet')
}
async function sharedModels(): Promise<SharedModels> {
  return import('@railgun-community/shared-models')
}

/**
 * Gas details used for both proof generation (informs the proof of the gas estimate) and the
 * actual tx submission. Values mirror legacy/usdc-v2-frontend — EIP-1559 (Type2) because Hardhat
 * (and our patched Railgun NetworkName.Hardhat) require it.
 *
 * 2 000 000 gas / 2 gwei max / 1 gwei priority — overkill for local but harmless; the user pays
 * actual usage. When Sepolia mode lands we'll likely sharpen these per chain.
 */
async function buildGasDetails(): Promise<unknown> {
  const { EVMGasType } = await sharedModels()
  return {
    evmGasType: EVMGasType.Type2,
    gasEstimate: 2_000_000n,
    maxFeePerGas: 2_000_000_000n,
    maxPriorityFeePerGas: 1_000_000_000n,
  }
}

/**
 * Generate the ZK unshield proof for a single recipient. Side-effect on the engine: the proof
 * is cached in memory keyed by the wallet + amounts, and the subsequent `populateProvedUnshield`
 * call must use the SAME inputs or it throws "proof not found".
 *
 * `onProgress` receives a value in [0, 1]; the SDK calls it ~10× over the proof generation
 * window (which is 20-30 seconds on local Anvil, longer on slower machines).
 */
export async function generateUnshieldProofForRecipient(opts: {
  walletId: string
  encryptionKey: string
  tokenAddress: string
  recipient: string
  amount: bigint
  onProgress?: (fraction: number) => void
}): Promise<void> {
  await loadHubNetwork()
  const [{ generateUnshieldProof }, { TXIDVersion, NetworkName }] = await Promise.all([
    railgunSdk(),
    sharedModels(),
  ])
  await generateUnshieldProof(
    TXIDVersion.V2_PoseidonMerkle,
    NetworkName.Hardhat,
    opts.walletId,
    opts.encryptionKey,
    [
      {
        tokenAddress: opts.tokenAddress,
        amount: opts.amount,
        recipientAddress: opts.recipient,
      },
    ],
    [], // nftAmountRecipients
    undefined, // broadcasterFeeRecipient — direct user submit, no relayer fee
    true, // sendWithPublicWallet
    undefined, // overallBatchMinGasPrice
    (progress) => opts.onProgress?.(progress / 100),
  )
}

/**
 * Populate the transaction object using the proof generated by `generateUnshieldProofForRecipient`.
 * Inputs MUST match the proof call exactly (walletId, recipient, amount, token).
 *
 * Returns the raw `to` + `data` + `value` from the SDK — the handler signs+submits via the
 * connected wallet rather than letting the SDK call its own provider (which would use a
 * non-user signer).
 */
export async function populateUnshieldTransaction(opts: {
  walletId: string
  tokenAddress: string
  recipient: string
  amount: bigint
}): Promise<{ to: `0x${string}`; data: `0x${string}`; value: bigint }> {
  const [{ populateProvedUnshield }, { TXIDVersion, NetworkName }] = await Promise.all([
    railgunSdk(),
    sharedModels(),
  ])
  const gasDetails = await buildGasDetails()
  const result = await populateProvedUnshield(
    TXIDVersion.V2_PoseidonMerkle,
    NetworkName.Hardhat,
    opts.walletId,
    [
      {
        tokenAddress: opts.tokenAddress,
        amount: opts.amount,
        recipientAddress: opts.recipient,
      },
    ],
    [], // nftAmountRecipients
    undefined, // broadcasterFeeRecipient
    true, // sendWithPublicWallet
    undefined, // overallBatchMinGasPrice
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    gasDetails as any,
  )
  const tx = result.transaction
  if (!tx.to || !tx.data) {
    throw new Error('populateUnshieldTransaction: SDK returned an incomplete transaction')
  }
  return {
    to: tx.to as `0x${string}`,
    data: tx.data as `0x${string}`,
    value: tx.value ? BigInt(tx.value.toString()) : 0n,
  }
}

/**
 * Cross-chain unshield: the proof is generated with the PrivacyPool itself as the unshield
 * recipient (the pool effectively burns the shielded UTXO and emits CCTP messages to deliver
 * USDC to the real recipient on a different chain). Same SDK fn, different recipient.
 */
export async function generateXchainUnshieldProof(opts: {
  walletId: string
  encryptionKey: string
  tokenAddress: string
  privacyPoolAddress: string
  amount: bigint
  onProgress?: (fraction: number) => void
}): Promise<void> {
  await loadHubNetwork()
  const [{ generateUnshieldProof }, { TXIDVersion, NetworkName }] = await Promise.all([
    railgunSdk(),
    sharedModels(),
  ])
  await generateUnshieldProof(
    TXIDVersion.V2_PoseidonMerkle,
    NetworkName.Hardhat,
    opts.walletId,
    opts.encryptionKey,
    [
      {
        tokenAddress: opts.tokenAddress,
        amount: opts.amount,
        // The PrivacyPool itself receives the USDC — it then forwards via CCTP. The actual user
        // recipient is encoded in the atomicCrossChainUnshield args (not the proof).
        recipientAddress: opts.privacyPoolAddress,
      },
    ],
    [],
    undefined,
    true,
    undefined,
    (progress) => opts.onProgress?.(progress / 100),
  )
}

/**
 * Populate the proof + decode the engine's `transact([tx])` calldata to extract the single
 * inner `Transaction` struct. We need the struct (not the calldata) because the cross-chain
 * entry point is `atomicCrossChainUnshield(tx, ...)` — same struct, different surrounding args.
 *
 * Returns a deeply-cloned mutable object with bigints restored (ethers v6 returns frozen
 * Result proxies and large-magnitude integers are stringified during the JSON deep-clone).
 */
export async function buildXchainUnshieldTransactionStruct(opts: {
  walletId: string
  tokenAddress: string
  privacyPoolAddress: string
  amount: bigint
}): Promise<unknown> {
  const [{ populateProvedUnshield }, { TXIDVersion, NetworkName }] = await Promise.all([
    railgunSdk(),
    sharedModels(),
  ])
  const { ethers } = await import('ethers')

  const gasDetails = await buildGasDetails()
  const result = await populateProvedUnshield(
    TXIDVersion.V2_PoseidonMerkle,
    NetworkName.Hardhat,
    opts.walletId,
    [
      {
        tokenAddress: opts.tokenAddress,
        amount: opts.amount,
        recipientAddress: opts.privacyPoolAddress,
      },
    ],
    [],
    undefined,
    true,
    undefined,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    gasDetails as any,
  )
  const calldata = result.transaction.data
  if (!calldata) {
    throw new Error('buildXchainUnshieldTransactionStruct: SDK returned no calldata')
  }

  // The SDK populates `transact([transaction])`; decode and pull the single inner struct.
  const TRANSACT_ABI = [
    'function transact((tuple(tuple(uint256 x, uint256 y) a, tuple(uint256[2] x, uint256[2] y) b, tuple(uint256 x, uint256 y) c) proof, bytes32 merkleRoot, bytes32[] nullifiers, bytes32[] commitments, tuple(uint16 treeNumber, uint72 minGasPrice, uint8 unshield, uint64 chainID, address adaptContract, bytes32 adaptParams, tuple(bytes32[4] ciphertext, bytes32 blindedSenderViewingKey, bytes32 blindedReceiverViewingKey, bytes annotationData, bytes memo)[] commitmentCiphertext) boundParams, tuple(bytes32 npk, tuple(uint8 tokenType, address tokenAddress, uint256 tokenSubID) token, uint120 value) unshieldPreimage)[] _transactions)',
  ]
  const iface = new ethers.Interface(TRANSACT_ABI)
  const decoded = iface.decodeFunctionData('transact', calldata)
  const transactions = decoded[0]
  if (!transactions || transactions.length === 0) {
    throw new Error('buildXchainUnshieldTransactionStruct: no transactions in decoded calldata')
  }

  // ethers v6 returns frozen `Result` proxies. Deep-clone via JSON (with bigint stringification)
  // and restore bigints where the contract expects them. Same trick the legacy app uses.
  const raw = transactions[0]
  const cloned = JSON.parse(
    JSON.stringify(raw, (_, v) => (typeof v === 'bigint' ? v.toString() : v)),
  )
  function restoreBigints(value: unknown): unknown {
    if (value === null || value === undefined) return value
    if (typeof value === 'string' && /^\d+$/.test(value) && value.length > 15) {
      return BigInt(value)
    }
    if (Array.isArray(value)) return value.map(restoreBigints)
    if (typeof value === 'object') {
      const out: Record<string, unknown> = {}
      for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
        out[k] = restoreBigints(v)
      }
      return out
    }
    return value
  }
  return restoreBigints(cloned)
}
